import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'app-language';
const SUPPORTED_LANGUAGES = ['en', 'hi', 'bho'];

const translations = {
  en: {
    common: {
      appName: 'Labor Connect India',
      language: 'Language',
      english: 'English',
      hindi: 'Hindi',
      bhojpuri: 'Bhojpuri',
      backToHome: 'Back to home',
      logout: 'Logout',
      consumer: 'Consumer',
      laborer: 'Worker',
      city: 'City',
      location: 'Location',
      budgetPerDay: 'Budget (per day)',
      deadline: 'Deadline',
      cancel: 'Cancel',
      open: 'Open',
      matched: 'Matched',
      allCities: 'All cities',
    },
    landing: {
      badge: 'Labor Connect India',
      title1: 'Hire trusted workers',
      title2: 'with confidence in your city',
      subtitle:
        'A modern labor marketplace for homeowners, contractors, and skilled professionals across Bihar.',
      employerTop: 'For Employers',
      workerTop: 'For Workers',
      employerTitle: 'I need workers',
      workerTitle: 'I offer services',
      employerCopy:
        'Post your project details and quickly connect with masons, helpers, electricians, painters, and more in your area.',
      workerCopy:
        'Build a stronger profile for your work, highlight your skills, and get discovered by customers looking for reliable local professionals.',
      startHiring: 'Start hiring',
      joinWorker: 'Join as a worker',
      chips: ['8+ Bihar cities', 'Trusted worker profiles', 'Multiple skilled trades'],
      footer: [
        'Live opportunities in Bihar',
        'Better worker-employer matching',
        'Professional first impression',
      ],
      consumerPoints: [
        'Post work requirements in minutes',
        'Discover verified local professionals',
        'Compare skills, location, and daily rates',
      ],
      laborerPoints: [
        'Showcase your expertise professionally',
        'Get matched with nearby projects faster',
        'Build trust with a polished worker profile',
      ],
    },
    consumerAuth: {
      portal: 'Consumer portal',
      welcomeBack: 'Welcome back',
      createAccountHero: 'Create your hiring account',
      heroCopy:
        'Manage requirements professionally, reach better workers faster, and present your project details in a way that builds trust.',
      heroPoints: [
        'Hire local workers by skill and location',
        'Share project needs clearly',
        'Keep your information secure',
      ],
      newAccount: 'New account',
      signIn: 'Sign in',
      formTitleSignup: 'Find the right workers faster',
      formTitleSignin: 'Access your employer dashboard',
      formCopySignup: 'Create a clean professional profile and start posting requirements.',
      formCopySignin: 'Sign in to manage your requirements and connect with skilled laborers.',
      fullName: 'Full name',
      email: 'Email address',
      password: 'Password',
      phone: 'Phone number',
      createButton: 'Create consumer account',
      loginButton: 'Sign in as consumer',
      alreadyHave: 'Already have an account?',
      noAccount: "Don't have an account?",
      createAccount: 'Create account',
      signInLink: 'Sign in',
      alert: 'Your data is only used to connect you with suitable workers.',
      locationPlaceholder: 'Select your city',
    },
    laborerAuth: {
      portal: 'Worker portal',
      welcomeBack: 'Welcome back',
      createAccountHero: 'Showcase your work professionally',
      heroCopy:
        'Present your skills, experience, and location more professionally so customers can trust you quickly and choose you with confidence.',
      heroPoints: [
        'Highlight your strongest skills',
        'Reach nearby employers faster',
        'Build a stronger professional profile',
      ],
      registration: 'Worker registration',
      signIn: 'Sign in',
      formTitleSignup: 'Create your worker profile',
      formTitleSignin: 'Access your worker dashboard',
      formCopySignup:
        'Add the details that help employers understand your value immediately.',
      formCopySignin: 'Sign in to view opportunities and manage your job applications.',
      fullName: 'Full name',
      email: 'Email address',
      password: 'Password',
      phone: 'Phone number',
      skills: 'Your skills',
      experience: 'Years of experience',
      createButton: 'Create worker account',
      loginButton: 'Sign in as worker',
      alreadyHave: 'Already have an account?',
      noAccount: "Don't have an account?",
      createAccount: 'Create account',
      signInLink: 'Sign in',
      alert: 'Your profile details help customers find and trust you more easily.',
      locationPlaceholder: 'Select your city',
    },
    consumerDashboard: {
      title: 'Find Skilled Laborers',
      subtitle: 'Post requirements or browse available workers',
      postRequirement: 'Post Requirement',
      browseWorkers: 'Browse Workers',
      myRequirements: 'My Requirements',
      searchPlaceholder: 'Search by name or skill...',
      contactWorker: 'Contact Worker',
      noRequirements: 'No requirements posted yet',
      postFirstRequirement: 'Post your first requirement',
      workersNeeded: 'Workers Needed',
      requiredSkills: 'Required Skills',
      postRequirementTitle: 'Post Requirement',
      description: 'Description',
      descriptionPlaceholder: 'Describe your project...',
      numberOfRajMistri: 'Number of Raj Mistri',
      numberOfLaborers: 'Number of Laborers',
      skillsRequiredOptional: 'Skills Required (Optional)',
      submitRequirement: 'Submit Requirement',
    },
    laborerDashboard: {
      title: 'My Dashboard',
      subtitle: 'Track your earnings and find new opportunities',
      availableJobs: 'Available Jobs',
      myApplications: 'My Applications',
      noAvailableJobs: 'No available jobs matching your profile',
      noApplications: 'No applications yet',
      checkBackLater: 'Check back later for new opportunities',
      startApplying: 'Start applying to available jobs',
      applied: 'Applied',
      workersNeeded: 'Workers Needed',
      budget: 'Budget',
      applyNow: 'Apply Now',
      deadlineLabel: 'Deadline',
      stats: {
        earnings: 'Total Earnings',
        completed: 'Jobs Completed',
        rating: 'Average Rating',
        active: 'Active Jobs',
      },
    },
  },
  hi: {
    common: {
      appName: 'लेबर कनेक्ट इंडिया',
      language: 'भाषा',
      english: 'अंग्रेज़ी',
      hindi: 'हिंदी',
      bhojpuri: 'भोजपुरी',
      backToHome: 'होम पर वापस जाएँ',
      logout: 'लॉगआउट',
      consumer: 'उपभोक्ता',
      laborer: 'मजदूर',
      city: 'शहर',
      location: 'स्थान',
      budgetPerDay: 'बजट (प्रति दिन)',
      deadline: 'अंतिम तिथि',
      cancel: 'रद्द करें',
      open: 'खुला',
      matched: 'मिल गया',
      allCities: 'सभी शहर',
    },
    landing: {
      badge: 'लेबर कनेक्ट इंडिया',
      title1: 'विश्वसनीय मजदूरों को रखें',
      title2: 'अपने शहर में भरोसे के साथ',
      subtitle:
        'बिहार के गृहस्वामियों, ठेकेदारों और कुशल पेशेवरों के लिए एक आधुनिक लेबर प्लेटफ़ॉर्म।',
      employerTop: 'नियोक्ताओं के लिए',
      workerTop: 'मजदूरों के लिए',
      employerTitle: 'मुझे मजदूर चाहिए',
      workerTitle: 'मैं सेवा देता हूँ',
      employerCopy:
        'अपने प्रोजेक्ट की जानकारी पोस्ट करें और अपने इलाके के राजमिस्त्री, हेल्पर, इलेक्ट्रिशियन, पेंटर और अन्य लोगों से जल्दी जुड़ें।',
      workerCopy:
        'अपने काम की प्रोफ़ाइल मज़बूत बनाइए, अपनी स्किल दिखाइए और भरोसेमंद स्थानीय ग्राहकों तक पहुँचिए।',
      startHiring: 'काम शुरू करें',
      joinWorker: 'वर्कर के रूप में जुड़ें',
      chips: ['8+ बिहार शहर', 'विश्वसनीय प्रोफ़ाइल', 'कई प्रकार के काम'],
      footer: ['बिहार में लाइव अवसर', 'बेहतर मिलान', 'प्रोफेशनल पहचान'],
      consumerPoints: [
        'कुछ मिनट में काम पोस्ट करें',
        'सत्यापित स्थानीय प्रोफेशनल खोजें',
        'रेट, स्किल और लोकेशन की तुलना करें',
      ],
      laborerPoints: [
        'अपनी विशेषज्ञता बेहतर ढंग से दिखाएँ',
        'पास के काम जल्दी पाएँ',
        'प्रोफेशनल प्रोफ़ाइल से भरोसा बनाएँ',
      ],
    },
    consumerAuth: {
      portal: 'उपभोक्ता पोर्टल',
      welcomeBack: 'वापसी पर स्वागत है',
      createAccountHero: 'अपना हायरिंग अकाउंट बनाइए',
      heroCopy:
        'अपनी आवश्यकताओं को प्रोफेशनल तरीके से मैनेज करें, बेहतर मजदूर जल्दी पाएँ और अपने प्रोजेक्ट को भरोसेमंद तरीके से पेश करें।',
      heroPoints: [
        'स्किल और लोकेशन के आधार पर मजदूर ढूँढें',
        'अपनी ज़रूरत साफ़ तरीके से बताइए',
        'आपकी जानकारी सुरक्षित रहती है',
      ],
      newAccount: 'नया अकाउंट',
      signIn: 'साइन इन',
      formTitleSignup: 'सही मजदूर जल्दी पाएँ',
      formTitleSignin: 'अपने डैशबोर्ड में जाएँ',
      formCopySignup: 'एक साफ़ प्रोफेशनल प्रोफ़ाइल बनाइए और काम पोस्ट करना शुरू कीजिए।',
      formCopySignin: 'साइन इन करके अपनी ज़रूरतें मैनेज करें और कुशल मजदूरों से जुड़ें।',
      fullName: 'पूरा नाम',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      phone: 'फ़ोन नंबर',
      createButton: 'उपभोक्ता अकाउंट बनाइए',
      loginButton: 'उपभोक्ता के रूप में साइन इन करें',
      alreadyHave: 'क्या आपका अकाउंट पहले से है?',
      noAccount: 'क्या आपका अकाउंट नहीं है?',
      createAccount: 'अकाउंट बनाइए',
      signInLink: 'साइन इन',
      alert: 'आपकी जानकारी केवल सही मजदूरों से जोड़ने के लिए उपयोग होती है।',
      locationPlaceholder: 'अपना शहर चुनें',
    },
    laborerAuth: {
      portal: 'मजदूर पोर्टल',
      welcomeBack: 'वापसी पर स्वागत है',
      createAccountHero: 'अपने काम को प्रोफेशनल तरीके से दिखाएँ',
      heroCopy:
        'अपनी स्किल, अनुभव और लोकेशन को बेहतर तरह से दिखाइए ताकि ग्राहक जल्दी भरोसा करें और आपको चुनें।',
      heroPoints: [
        'अपनी सबसे अच्छी स्किल दिखाइए',
        'पास के नियोक्ताओं तक जल्दी पहुँचिए',
        'मज़बूत प्रोफेशनल प्रोफ़ाइल बनाइए',
      ],
      registration: 'मजदूर रजिस्ट्रेशन',
      signIn: 'साइन इन',
      formTitleSignup: 'अपनी प्रोफ़ाइल बनाइए',
      formTitleSignin: 'अपने डैशबोर्ड में जाएँ',
      formCopySignup: 'ऐसी जानकारी जोड़ें जिससे नियोक्ता आपकी वैल्यू तुरंत समझ सके।',
      formCopySignin: 'साइन इन करके अवसर देखें और अपनी एप्लिकेशन मैनेज करें।',
      fullName: 'पूरा नाम',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      phone: 'फ़ोन नंबर',
      skills: 'आपकी स्किल',
      experience: 'अनुभव के वर्ष',
      createButton: 'मजदूर अकाउंट बनाइए',
      loginButton: 'मजदूर के रूप में साइन इन करें',
      alreadyHave: 'क्या आपका अकाउंट पहले से है?',
      noAccount: 'क्या आपका अकाउंट नहीं है?',
      createAccount: 'अकाउंट बनाइए',
      signInLink: 'साइन इन',
      alert: 'आपकी प्रोफ़ाइल की जानकारी ग्राहकों को आपको जल्दी ढूँढने और भरोसा करने में मदद करती है।',
      locationPlaceholder: 'अपना शहर चुनें',
    },
    consumerDashboard: {
      title: 'कुशल मजदूर खोजें',
      subtitle: 'अपनी आवश्यकता पोस्ट करें या उपलब्ध मजदूर देखें',
      postRequirement: 'आवश्यकता पोस्ट करें',
      browseWorkers: 'मजदूर देखें',
      myRequirements: 'मेरी आवश्यकताएँ',
      searchPlaceholder: 'नाम या स्किल से खोजें...',
      contactWorker: 'मजदूर से संपर्क करें',
      noRequirements: 'अभी तक कोई आवश्यकता पोस्ट नहीं की गई है',
      postFirstRequirement: 'अपनी पहली आवश्यकता पोस्ट करें',
      workersNeeded: 'ज़रूरी मजदूर',
      requiredSkills: 'ज़रूरी स्किल',
      postRequirementTitle: 'आवश्यकता पोस्ट करें',
      description: 'विवरण',
      descriptionPlaceholder: 'अपने प्रोजेक्ट का विवरण लिखें...',
      numberOfRajMistri: 'राज मिस्त्री की संख्या',
      numberOfLaborers: 'मज़दूरों की संख्या',
      skillsRequiredOptional: 'ज़रूरी स्किल (वैकल्पिक)',
      submitRequirement: 'आवश्यकता जमा करें',
    },
    laborerDashboard: {
      title: 'मेरा डैशबोर्ड',
      subtitle: 'अपनी कमाई ट्रैक करें और नए अवसर खोजें',
      availableJobs: 'उपलब्ध काम',
      myApplications: 'मेरे आवेदन',
      noAvailableJobs: 'आपकी प्रोफ़ाइल से मेल खाने वाला कोई काम उपलब्ध नहीं है',
      noApplications: 'अभी तक कोई आवेदन नहीं है',
      checkBackLater: 'नए अवसरों के लिए बाद में फिर देखें',
      startApplying: 'उपलब्ध कामों पर आवेदन करना शुरू करें',
      applied: 'आवेदन किया गया',
      workersNeeded: 'ज़रूरी मजदूर',
      budget: 'बजट',
      applyNow: 'अभी आवेदन करें',
      deadlineLabel: 'अंतिम तिथि',
      stats: {
        earnings: 'कुल कमाई',
        completed: 'पूरा किए गए काम',
        rating: 'औसत रेटिंग',
        active: 'सक्रिय काम',
      },
    },
  },
  bho: {
    common: {
      appName: 'लेबर कनेक्ट इंडिया',
      language: 'भाषा',
      english: 'अंग्रेजी',
      hindi: 'हिंदी',
      bhojpuri: 'भोजपुरी',
      backToHome: 'होम पर वापस जाईं',
      logout: 'लॉगआउट',
      consumer: 'ग्राहक',
      laborer: 'मजदूर',
      city: 'शहर',
      location: 'जगह',
      budgetPerDay: 'बजट (दिन के हिसाब से)',
      deadline: 'आखिरी तारीख',
      cancel: 'रद्द करीं',
      open: 'खुलल',
      matched: 'मिलल',
      allCities: 'सभे शहर',
    },
    landing: {
      badge: 'लेबर कनेक्ट इंडिया',
      title1: 'भरोसेमंद मजदूर राखीं',
      title2: 'अपने शहर में भरोसा के साथ',
      subtitle:
        'बिहार के घर मालिक, ठेकेदार आ कुशल कामगार खातिर एगो आधुनिक लेबर प्लेटफॉर्म।',
      employerTop: 'नियोक्ता खातिर',
      workerTop: 'मजदूर खातिर',
      employerTitle: 'हमके मजदूर चाहीं',
      workerTitle: 'हम काम देत बानी',
      employerCopy:
        'अपना प्रोजेक्ट के जानकारी पोस्ट करीं आ अपना इलाका के राजमिस्त्री, हेल्पर, इलेक्ट्रिशियन, पेंटर आ अउरी लोगन से जल्दी जुड़ीं।',
      workerCopy:
        'अपना काम के प्रोफाइल मजबूत बनाईं, अपना स्किल देखाईं आ भरोसेमंद स्थानीय ग्राहक तक पहुंचीं।',
      startHiring: 'काम शुरू करीं',
      joinWorker: 'वर्कर बन के जुड़ीं',
      chips: ['8+ बिहार शहर', 'भरोसेमंद प्रोफाइल', 'अलग-अलग काम'],
      footer: ['बिहार में लाइव अवसर', 'बेहतर मिलान', 'प्रोफेशनल पहचान'],
      consumerPoints: [
        'कुछ मिनट में काम पोस्ट करीं',
        'सही स्थानीय प्रोफेशनल खोजीं',
        'रेट, स्किल आ लोकेशन मिलाईं',
      ],
      laborerPoints: [
        'अपना हुनर के बढ़िया ढंग से देखाईं',
        'नजदीक के काम जल्दी पाइं',
        'प्रोफेशनल प्रोफाइल से भरोसा बनाईं',
      ],
    },
    consumerAuth: {
      portal: 'ग्राहक पोर्टल',
      welcomeBack: 'फेर से स्वागत बा',
      createAccountHero: 'अपना हायरिंग अकाउंट बनाईं',
      heroCopy:
        'अपना जरूरत के बढ़िया ढंग से मैनेज करीं, सही मजदूर जल्दी पाईं आ अपना प्रोजेक्ट के भरोसेमंद तरीका से देखाईं।',
      heroPoints: [
        'स्किल आ जगह के हिसाब से मजदूर खोजीं',
        'अपना जरूरत साफ-साफ बताईं',
        'राउर जानकारी सुरक्षित रहेला',
      ],
      newAccount: 'नया अकाउंट',
      signIn: 'साइन इन',
      formTitleSignup: 'सही मजदूर जल्दी पाईं',
      formTitleSignin: 'अपना डैशबोर्ड में जाईं',
      formCopySignup: 'एक साफ-सुथर प्रोफेशनल प्रोफाइल बनाईं आ काम पोस्ट शुरू करीं।',
      formCopySignin: 'साइन इन करके अपना जरूरत मैनेज करीं आ कुशल मजदूर से जुड़ीं।',
      fullName: 'पूरा नाम',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      phone: 'फोन नंबर',
      createButton: 'ग्राहक अकाउंट बनाईं',
      loginButton: 'ग्राहक के रूप में साइन इन करीं',
      alreadyHave: 'पहिले से अकाउंट बा?',
      noAccount: 'अकाउंट नइखे?',
      createAccount: 'अकाउंट बनाईं',
      signInLink: 'साइन इन',
      alert: 'राउर जानकारी खाली सही मजदूर से जोड़ल खातिर इस्तेमाल होई।',
      locationPlaceholder: 'अपना शहर चुनीं',
    },
    laborerAuth: {
      portal: 'मजदूर पोर्टल',
      welcomeBack: 'फेर से स्वागत बा',
      createAccountHero: 'अपना काम के प्रोफेशनल तरीका से देखाईं',
      heroCopy:
        'अपना स्किल, अनुभव आ जगह के बढ़िया तरीका से देखाईं ताकि ग्राहक जल्दी भरोसा करे आ रउआ के चुने।',
      heroPoints: [
        'अपना बढ़िया स्किल देखाईं',
        'नजदीक के नियोक्ता तक जल्दी पहुंचीं',
        'मजबूत प्रोफेशनल प्रोफाइल बनाईं',
      ],
      registration: 'मजदूर रजिस्ट्रेशन',
      signIn: 'साइन इन',
      formTitleSignup: 'अपना प्रोफाइल बनाईं',
      formTitleSignin: 'अपना डैशबोर्ड में जाईं',
      formCopySignup: 'ओह जानकारी के जोड़ दीं जवन नियोक्ता के राउर वैल्यू तुरंत समझा दे।',
      formCopySignin: 'साइन इन करके अवसर देखीं आ अपना आवेदन मैनेज करीं।',
      fullName: 'पूरा नाम',
      email: 'ईमेल पता',
      password: 'पासवर्ड',
      phone: 'फोन नंबर',
      skills: 'राउर स्किल',
      experience: 'अनुभव के साल',
      createButton: 'मजदूर अकाउंट बनाईं',
      loginButton: 'मजदूर के रूप में साइन इन करीं',
      alreadyHave: 'पहिले से अकाउंट बा?',
      noAccount: 'अकाउंट नइखे?',
      createAccount: 'अकाउंट बनाईं',
      signInLink: 'साइन इन',
      alert: 'राउर प्रोफाइल के जानकारी ग्राहक के रउआ के जल्दी खोजे आ भरोसा करे में मदद करेला।',
      locationPlaceholder: 'अपना शहर चुनीं',
    },
    consumerDashboard: {
      title: 'कुशल मजदूर खोजीं',
      subtitle: 'अपना जरूरत पोस्ट करीं या उपलब्ध मजदूर देखीं',
      postRequirement: 'जरूरत पोस्ट करीं',
      browseWorkers: 'मजदूर देखीं',
      myRequirements: 'हमार जरूरत',
      searchPlaceholder: 'नाम या स्किल से खोजीं...',
      contactWorker: 'मजदूर से संपर्क करीं',
      noRequirements: 'अभी ले कौनो जरूरत पोस्ट नइखे भइल',
      postFirstRequirement: 'अपना पहिला जरूरत पोस्ट करीं',
      workersNeeded: 'जरूरी मजदूर',
      requiredSkills: 'जरूरी स्किल',
      postRequirementTitle: 'जरूरत पोस्ट करीं',
      description: 'विवरण',
      descriptionPlaceholder: 'अपना प्रोजेक्ट के बारे में लिखीं...',
      numberOfRajMistri: 'राज मिस्त्री के संख्या',
      numberOfLaborers: 'मजदूरन के संख्या',
      skillsRequiredOptional: 'जरूरी स्किल (वैकल्पिक)',
      submitRequirement: 'जरूरत जमा करीं',
    },
    laborerDashboard: {
      title: 'हमार डैशबोर्ड',
      subtitle: 'अपना कमाई देखीं आ नया अवसर खोजीं',
      availableJobs: 'उपलब्ध काम',
      myApplications: 'हमार आवेदन',
      noAvailableJobs: 'राउर प्रोफाइल से मिले वाला कौनो काम उपलब्ध नइखे',
      noApplications: 'अभी ले कौनो आवेदन नइखे',
      checkBackLater: 'नया मौका खातिर बाद में फेर देखीं',
      startApplying: 'उपलब्ध काम पर आवेदन शुरू करीं',
      applied: 'आवेदन भइल',
      workersNeeded: 'जरूरी मजदूर',
      budget: 'बजट',
      applyNow: 'अभी आवेदन करीं',
      deadlineLabel: 'आखिरी तारीख',
      stats: {
        earnings: 'कुल कमाई',
        completed: 'पूरा काम',
        rating: 'औसत रेटिंग',
        active: 'चल रहल काम',
      },
    },
  },
};

const LanguageContext = createContext(undefined);

function getInitialLanguage() {
  const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (SUPPORTED_LANGUAGES.includes(storedLanguage)) {
    return storedLanguage;
  }

  const browserLanguage = navigator.language?.toLowerCase() || '';
  if (browserLanguage.startsWith('hi')) {
    return 'hi';
  }

  return 'en';
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  }, [language]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: translations[language],
      languageOptions: [
        { value: 'en', label: translations[language].common.english },
        { value: 'hi', label: translations[language].common.hindi },
        { value: 'bho', label: translations[language].common.bhojpuri },
      ],
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);

  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }

  return context;
}
